### ISSUE TITLE
Unhandled promise: Converting circular structure to JSON

### ISSUE THREAD

**Issue by maxvisser** [alertlogic/cwe-collector#60]
I got an error while deploying cloudformation template.

``
2020-02-18T15:22:17.730Z c1c8ac68-2111-4068-a6e2-d49248e7aa39 ERROR Unhandled Promise Rejection {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: Converting circular structure to JSON","reason":{"errorType":"TypeError","errorMessage":"Converting circular structure to JSON","stack":["TypeError: Converting circular structure to JSON"," at JSON.stringify (<anonymous>)"," at Object.exports.send (/var/task/node_modules/cfn-response/index.js:13:29)"," at _azcollectc.deregister.then.catch.exception (/var/task/node_modules/@alertlogic/al-aws-collector-js/al_aws_collector.js:247:33)"," at process._tickCallback (internal/process/next_tick.js:68:7)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: Converting circular structure to JSON"," at process.on (/var/runtime/index.js:37:15)"," at process.emit (events.js:198:13)"," at process.EventEmitter.emit (domain.js:448:20)"," at emitPromiseRejectionWarnings (internal/process/promises.js:140:18)"," at process._tickCallback (internal/process/next_tick.js:69:34)``

**Comment by OHaganA** [comment]
Hi Max,
This is an issue with your AIMS keys; the keys used to authenticate against the Alert Logic backend. In your case, these keys are invalid, and the first HTTP request to our backend is failing because of this. This error is then propagated forward resulting in the error you posted

**Comment by maxvisser** [comment]
I will look into this and rerun the script.

**Comment by OHaganA** [comment]
Hi @maxvisser, have you encountered any more issues with this or can we close the issue?

**Comment by maxvisser** [comment]
I still need to rerun the script. I will dot this right now; it was abit of my radar. I will comment again in a few minutes

**Comment by maxvisser** [comment]
Ah I see what I did wrong. You can close this issue.

**Comment by OHaganA** [comment]
Ah, thanks for updating!
